import React,{useEffect,useState}from"react";
import{Bot,CheckCircle2,ChevronRight,Lightbulb,RotateCcw,Send,Sparkles,Trophy,X}from"lucide-react";

const sections=[
{id:"welcome",title:"Welcome to Java",body:<><p>Java is the language we will use to build our Minecraft mods. You do <b>not</b> need to know everything about Java before starting.</p><p>Think of Java as a language for giving the computer instructions. Minecraft and Fabric provide useful tools; your job is to combine them.</p><div className="tip"><Lightbulb/><div><b>Beginner rule</b><p>Do not try to memorize every symbol. Learn what each piece does, then practice changing it.</p></div></div></>},
{id:"variables",title:"1. Variables: storing information",body:<><p>A variable is a named place where your program can keep a value.</p><Code text={"String playerName = \"Alex\";\nint diamonds = 12;\ndouble speed = 0.25;\nboolean hasPermission = true;"}/><div className="explainGrid"><div><b>String</b><span>Text such as a player name.</span></div><div><b>int</b><span>Whole numbers such as 12.</span></div><div><b>double</b><span>Numbers that can contain decimals.</span></div><div><b>boolean</b><span>Either true or false.</span></div></div><p>For Minecraft mods, variables might store a player's name, a block count, a setting, or whether something is enabled.</p></>},
{id:"strings",title:"2. Text and numbers",body:<><p>You will constantly work with text and numbers in mods.</p><Code text={"String name = \"Steve\";\nint level = 5;\n\nSystem.out.println(name);\nSystem.out.println(\"Level: \" + level);"}/><p>The <code>+</code> joins text together. This is called <b>concatenation</b>.</p><div className="miniExercise"><b>Try it:</b><span>Change <code>level</code> to <code>10</code>. What do you think the second line prints?</span></div></>},
{id:"conditions",title:"3. Making decisions with if",body:<><p>Mods often need to ask a question: Is the player holding an item? Is a value high enough? Is a setting enabled?</p><Code text={"int diamonds = 12;\n\nif (diamonds >= 10) {\n    System.out.println(\"You have enough!\");\n} else {\n    System.out.println(\"You need more.\");\n}"}/><p>An <code>if</code> runs its code when the condition is true. <code>else</code> handles the other case.</p><div className="tip"><Lightbulb/><div><b>Read it like English</b><p>If diamonds are greater than or equal to 10, say enough. Otherwise, say need more.</p></div></div></>},
{id:"methods",title:"4. Methods: reusable actions",body:<><p>A method is a named group of instructions. Methods keep your code organized and let you reuse an action.</p><Code text={"public static void sayHello(String name) {\n    System.out.println(\"Hello, \" + name);\n}\n\nsayHello(\"Alex\");\nsayHello(\"Sam\");"}/><p>Here, <code>name</code> is a parameter. Each time we call the method, we give it a different value.</p><div className="miniExercise"><b>Think:</b><span>What would <code>sayHello("Steve")</code> print?</span></div></>},
{id:"classes",title:"5. Classes and objects",body:<><p>A class is a blueprint. An object is a real thing created from that blueprint.</p><Code text={"public class Pet {\n    String name;\n\n    public Pet(String name) {\n        this.name = name;\n    }\n}\n\nPet myPet = new Pet(\"Buddy\");"}/><p>In Minecraft, you will work with many objects: players, worlds, items, blocks, entities, and more.</p><div className="analogy"><b>Simple analogy</b><span>Class = blueprint for a house. Object = an actual house built from that blueprint.</span></div></>},
{id:"loops",title:"6. Loops: repeating work",body:<><p>A loop repeats code. This becomes useful when you need to process several things.</p><Code text={"for (int i = 0; i < 5; i++) {\n    System.out.println(\"Count: \" + i);\n}"}/><p>This prints five lines. The counter starts at 0 and increases until it reaches 5.</p><div className="warning"><b>Important for Minecraft:</b><span>Do not put huge loops into game code without understanding how much work they do. Performance matters.</span></div></>},
{id:"minecraft",title:"7. How this connects to Minecraft",body:<><p>Now connect the Java ideas to modding:</p><div className="mapping"><div><b>Java variable</b><span>Stores a setting, name, number, or object.</span></div><div><b>Java method</b><span>Performs one action.</span></div><div><b>Java class</b><span>Organizes related code and represents objects.</span></div><div><b>if statement</b><span>Lets your mod react differently to different situations.</span></div><div><b>loop</b><span>Repeats work when you actually need repetition.</span></div></div></>},
{id:"challenge",title:"8. Your first mini challenge",body:<><p>Write a tiny Java program that stores a player's name and number of diamonds, then prints a message.</p><Code text={"String playerName = \"YOUR_NAME\";\nint diamonds = 15;\n\nif (diamonds >= 10) {\n    System.out.println(playerName + \" has enough diamonds!\");\n} else {\n    System.out.println(playerName + \" needs more diamonds.\");\n}"}/><p><b>Your job:</b> Change the name and number. Then predict which message will print before running it.</p><div className="challengeSteps"><span>1. Change the name.</span><span>2. Change the diamond count.</span><span>3. Predict the output.</span><span>4. Run it and compare.</span></div></>},
{id:"checkpoint",title:"9. Lesson checkpoint",body:<><p>Finish the checkpoint quiz to unlock Lesson 1. You need <b>80% or higher</b> to pass.</p><div className="checklist"><label>☐ I know what a variable is.</label><label>☐ I can recognize String, int, double, and boolean.</label><label>☐ I understand what an if/else statement does.</label><label>☐ I understand what a method is.</label><label>☐ I understand class vs object.</label><label>☐ I know what a loop does.</label></div><Quiz quiz={quiz} answers={quizAnswers} setAnswers={setQuizAnswers} submitted={quizSubmitted} setSubmitted={setQuizSubmitted} onPass={()=>setDone(d=>d.includes("java")?d:[...d,"java"])} /></>}
];

function Code({text}){return <pre className="code"><code>{text}</code><button onClick={()=>navigator.clipboard?.writeText(text)}>Copy</button></pre>}

export default function JavaLesson({done,setDone,ai,setAi}){
const[section,setSection]=useState("welcome");
const current=sections.find(x=>x.id===section)||sections[0];
const index=sections.findIndex(x=>x.id===section);
const[reset,setReset]=useState(false);
const[quizAnswers,setQuizAnswers]=useState({});
const[quizSubmitted,setQuizSubmitted]=useState(false);
const quiz=[
{q:"Which type stores text?",a:"String",o:["int","String","boolean","double"]},
{q:"What does int store?",a:"Whole numbers",o:["Text","true/false","Whole numbers","Decimal numbers"]},
{q:"What does an if statement do?",a:"Makes a decision",o:["Repeats forever","Makes a decision","Creates a class","Copies code"]},
{q:"What is a method?",a:"A named group of instructions",o:["A variable type","A named group of instructions","A Minecraft block","A number"]},
{q:"A class is best described as a...",a:"Blueprint",o:["Blueprint","Loop","Number","Condition"]},
{q:"What does a loop do?",a:"Repeats code",o:["Deletes code","Repeats code","Creates a player","Stores text"]},
{q:"Which value is a boolean?",a:"true",o:["12","\"Alex\"","0.25","true"]},
{q:"What does + do in \"Level: \" + level?",a:"Joins values into text",o:["Subtracts","Joins values into text","Creates a loop","Checks permission"]},
{q:"What does new Pet(\"Buddy\") create?",a:"An object",o:["A class","An object","A boolean","A method"]},
{q:"What should you do when an error appears?",a:"Read the first error and check its line",o:["Delete the whole project","Ignore it","Read the first error and check its line","Restart Minecraft only"]}
];
useEffect(()=>setSection("welcome"),[]);
return <div className="javaLesson">
<div className="lessonTop"><div><div className="meta"><span>BEGINNER</span><span>LESSON 1</span><span>45–60 MIN</span></div><h1>Java Foundations</h1><p className="lead">Your first step into Minecraft modding. We will learn Java one small idea at a time, then connect it to Minecraft.</p></div><button className="resetBtn" onClick={()=>setReset(!reset)}><RotateCcw size={14}/> Reset</button></div>
<div className="lessonProgress"><div><i style={{width:((index+1)/sections.length*100)+"%"}}/></div><span>Part {index+1} of {sections.length}</span></div>
<div className="beginnerLayout"><div>
<div className="lessonNav">{sections.map((x,i)=><button className={section===x.id?"lessonPart active":"lessonPart"} key={x.id} onClick={()=>setSection(x.id)}><span>{String(i+1).padStart(2,"0")}</span>{x.title}</button>)}</div>
{reset&&<div className="resetBox">This only resets the open section.<button onClick={()=>{setSection("welcome");setReset(false)}}>Start Lesson 1 from the beginning</button></div>}
<div className="sectionContent"><span className="sectionEyebrow">PART {index+1}</span><h2>{current.title}</h2>{current.body}</div>
<div className="lessonBottom"><button className="secondary" disabled={index===0} onClick={()=>setSection(sections[Math.max(0,index-1)].id)}>← Previous</button>{index<sections.length-1?<button className="primary" onClick={()=>setSection(sections[index+1].id)}>Next <ChevronRight size={16}/></button>:<span className="quizLock">Pass the 80% checkpoint to complete</span>}</div>
{index===sections.length-1&&done.includes("java")&&<div className="completeBanner"><Trophy size={20}/><div><b>Lesson 1 complete!</b><span>Next up: setting up your Fabric mod workspace.</span></div></div>}
</div>
<div className="sideLessonCard"><Sparkles/><b>Beginner mindset</b><p>It is normal for Java to feel weird at first. Read code slowly and ask: “What information is this storing?” and “What action is this doing?”</p><button className="secondary" onClick={()=>setAi(true)}><Bot size={15}/> Ask AI Tutor</button></div>
</div>
{ai&&<AITutor section={current.title} onClose={()=>setAi(false)}/>}
</div>
}

function AITutor({section,onClose}){
const[input,setInput]=useState("");
const[messages,setMessages]=useState([{from:"ai",text:"Hi! I'm your AI Tutor for Lesson 1. Ask me about Java, the current section, an error, or what a piece of code means."}]);
const answer=msg=>{const m=msg.toLowerCase();if(m.includes("variable"))return"A variable is a named place for a value. Example: int diamonds = 12; stores the number 12 under the name diamonds.";if(m.includes("if")||m.includes("else"))return"An if statement makes a decision. The code inside runs when its condition is true. else is what happens when it is false.";if(m.includes("method"))return"A method is a named group of instructions you can call. In sayHello(\"Alex\"), sayHello is the method.";if(m.includes("class")||m.includes("object"))return"A class is a blueprint and an object is an actual thing created from it. Pet is the class; new Pet(\"Buddy\") creates an object.";if(m.includes("loop")||m.includes("for"))return"A loop repeats code. Our for loop starts at 0, checks i < 5, runs the code, then increases i.";if(m.includes("error")||m.includes("broken"))return"Start with the first error message. Check the line number, spelling, brackets, semicolons, and whether your names match.";if(m.includes("minecraft")||m.includes("mod"))return"Java is the foundation. Fabric gives your mod Minecraft-specific APIs. Soon you'll use these Java ideas to register items, blocks, commands, and events.";return "For this section, first explain what you think the code is doing. Then tell me the exact word or line that confuses you."};
const send=()=>{if(!input.trim())return;const user=input.trim();setMessages(x=>[...x,{from:"user",text:user},{from:"ai",text:answer(user)}]);setInput("")};
return <div className="aiTutor"><div className="aiHeader"><div><Bot size={19}/><div><b>AI Tutor</b><small>Lesson 1 helper</small></div></div><button onClick={onClose}><X size={17}/></button></div><div className="aiContext">Section: <b>{section}</b></div><div className="aiMessages">{messages.map((m,i)=><div className={m.from==="ai"?"aiMsg":"userMsg"} key={i}>{m.text}</div>)}</div><div className="aiQuick"><button onClick={()=>setInput("What is a variable?")}>Variable</button><button onClick={()=>setInput("I have an error")}>Error help</button><button onClick={()=>setInput("Explain this")}>Explain</button></div><div className="aiInput"><input value={input} placeholder="Ask for help..." onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()}/><button onClick={send}><Send size={15}/></button></div></div>
}){
const[input,setInput]=useState("");
const[messages,setMessages]=useState([{from:"ai",text:"Hi! I'm your AI Tutor for Lesson 1. Ask me about Java, the current section, an error, or what a piece of code means."}]);
const answer=msg=>{const m=msg.toLowerCase();if(m.includes("variable"))return"A variable is a named place for a value. Example: int diamonds = 12; stores the number 12 under the name diamonds.";if(m.includes("if")||m.includes("else"))return"An if statement makes a decision. The code inside runs when its condition is true. else is what happens when it is false.";if(m.includes("method"))return"A method is a named group of instructions you can call. In sayHello(\"Alex\"), sayHello is the method.";if(m.includes("class")||m.includes("object"))return"A class is a blueprint and an object is an actual thing created from it. Pet is the class; new Pet(\"Buddy\") creates an object.";if(m.includes("loop")||m.includes("for"))return"A loop repeats code. Our for loop starts at 0, checks i < 5, runs the code, then increases i.";if(m.includes("error")||m.includes("broken"))return"Start with the first error message. Check the line number, spelling, brackets, semicolons, and whether your names match.";if(m.includes("minecraft")||m.includes("mod"))return"Java is the foundation. Fabric gives your mod Minecraft-specific APIs. Soon you'll use these Java ideas to register items, blocks, commands, and events.";return "For this section, first explain what you think the code is doing. Then tell me the exact word or line that confuses you."};
const send=()=>{if(!input.trim())return;const user=input.trim();setMessages(x=>[...x,{from:"user",text:user},{from:"ai",text:answer(user)}]);setInput("")};
return <div className="aiTutor"><div className="aiHeader"><div><Bot size={19}/><div><b>AI Tutor</b><small>Lesson 1 helper</small></div></div><button onClick={onClose}><X size={17}/></button></div><div className="aiContext">Section: <b>{section}</b></div><div className="aiMessages">{messages.map((m,i)=><div className={m.from==="ai"?"aiMsg":"userMsg"} key={i}>{m.text}</div>)}</div><div className="aiQuick"><button onClick={()=>setInput("What is a variable?")}>Variable</button><button onClick={()=>setInput("I have an error")}>Error help</button><button onClick={()=>setInput("Explain this")}>Explain</button></div><div className="aiInput"><input value={input} placeholder="Ask for help..." onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()}/><button onClick={send}><Send size={15}/></button></div></div>
}
